### ISSUE TITLE
 error starting dependencies

### ISSUE THREAD

**Issue by ghost** [Lookyan/jaeger-dependencies#2]
```
Failed to create index: Put http://elasticsearch:9200/jaeger-dependencies-2020-02-19: dial tcp 172.25.0.2:9200: connect: connection refused
dependencias_1   | 2020/02/19 10:42:04 Warning Delete http://elasticsearch:9200/jaeger-dependencies-2020-02-19: dial tcp 172.25.0.2:9200: connect: connection refused
```

my docker-compose configuration:

```
dependencias:
    image: lookyan/jaeger-dependencies:latest
    hostname: dependencias
    environment:
      - ES_HOST=http://elasticsearch:9200
    command: /bin/sh -c "sleep 60 && jaeger-dependencies"
    restart: always
    networks:
      - elastic-jaeger
    depends_on:
      - elasticsearch
```
